spring:
  application:
    name: api-gateway
  jackson:
    default-property-inclusion: NON_NULL
  sleuth:
    sampler:
      probability: 1.0
  cloud:
    gateway:
      #      routes:
      #        - id: bank-account
      #          uri: lb://bank-account-service
      #          predicates:
      #            - Path=/bank-account/**
      #          filters:
      #            - JwtAuthenticationFilter=RSA256,HS256
      #            - RemoveResponseHeader=X-Powered-By
      #        - id: order
      #          uri: lb://order-service
      #          predicates:
      #            - Path=/order/**
      #          filters:
      #            - JwtAuthenticationFilter=RSA256,HS256
      #            - RemoveResponseHeader=X-Powered-By
      discovery:
        locator:
          enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 9000

eureka:
  client:
    serviceURL:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}:${random.uuid}

#secret key - should be encrypted
jwt:
  secret: yanglain
  #ignore null fields in json
